### ISSUE TITLE
Dashboard.py - "import matplotlib"

### ISSUE THREAD

**Issue by Notnumbersix** [IkerGarcia/DashboardPi#2]
Hi - I'm working with the tutorial in The MagPi for the SenseHat temperature recorder.

I've installed the matplotlib libraries, as per instructions at magpi.cc/1TSwgAt, but when I run the Python program it returns an error - ImportError: No module named 'matplotlib'

I can't see what's causing this. Would someone be able to point me in the right direction please? Thank you.

Charles

**Comment by IkerGarcia** [comment]
Hi,

FIrst of all, thank you for trying to use DashboardPi, it is always glad to see that someone finds what took me some work useful. 

I am a bit busy right now to check everything you did, just try changing #!/usr/bin/env python and write down #!/usr/bin/python

If it doesn't work, execute python --version in the terminal and post here the result. 

Regards, 

Iker.

**Comment by Notnumbersix** [comment]
Hi Iker

thanks for your response - no problem, I'm in no rush, it's good to have such things to learn from. Changing the text didn't make any difference but, with the mention of versions, I tried it with Python2 (I'd been using Python3) and it works fine. So presumably that makes a difference, I'll have to look up why. Thanks very much for your help.

So that I could test that the data was been added to the graph/picture and to the CSV file I changed the time.sleep() value from 3600 to 30 so that it ran every thirty seconds. I've attached the csv file to show the result - very good. There does seem a little disrcrepancy with the time interval, which is more than the 30 seconds specified. I expect that this is due to the program taking time to do other things as well?

Thanks again, regards, Charles

**Comment by IkerGarcia** [comment]
Hi Charles, 

I made a mistake the other day and didn't post the full fix. As I told you I was busy and posted faster than I should, but excuse me for that. However, I am happy that you fixed it. I was asking about the version due to the fact that, depending on which Python version you use the library is installed in a different path, that was the problem when you were trying to run it.

Regarding to your question about the time.sleep(), probably the main drawback of matplotlib is that it is not very fast. This, specially when trying to plot a lot of data, creates that discrepancy. 

I believe that everything is ok now. If it is, close this thread if you want.

Thank you for using DashboardPi and if you create anything interesting feel free to push it!

Regards, 

Iker.
